#pragma once
#include "FN_Basic.h"

#include "FN_AnimNotifyState_DisableSteering_parameters.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_Engine_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: AnimNotifyState_DisableSteering
*/

// BlueprintGeneratedClass /Game/Animation/AnimNotifies/AnimNotifyState/AnimNotifyState_DisableSteering.AnimNotifyState_DisableSteering_C
// 0x0000 (0x001C)
class UAnimNotifyState_DisableSteering_C : public UAnimNotifyState
{
public:
	bool Received_NotifyEnd(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation); // Function /Game/Animation/AnimNotifies/AnimNotifyState/AnimNotifyState_DisableSteering.AnimNotifyState_DisableSteering_C:Received_NotifyEnd
	bool Received_NotifyBegin(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, float TotalDuration); // Function /Game/Animation/AnimNotifies/AnimNotifyState/AnimNotifyState_DisableSteering.AnimNotifyState_DisableSteering_C:Received_NotifyBegin
public:
	static class UClass* StaticClass();
};

