#pragma once
#include "FN_Basic.h"

#include "FN_AnimNotify_PlayReloadFX_parameters.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_Engine_classes.h"
#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: AnimNotify_PlayReloadFX
*/

// BlueprintGeneratedClass /Game/Animation/AnimNotifies/AnimNotifyEvent/AnimNotify_PlayReloadFX.AnimNotify_PlayReloadFX_C
// 0x0001 (0x0021)
class UAnimNotify_PlayReloadFX_C : public UAnimNotify
{
public:
	EFortReloadFXState                                                                                   ReloadStage;                                       // 0x0020 (0x0001)
public:
	bool Received_Notify(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation); // Function /Game/Animation/AnimNotifies/AnimNotifyEvent/AnimNotify_PlayReloadFX.AnimNotify_PlayReloadFX_C:Received_Notify
public:
	static class UClass* StaticClass();
};

