#pragma once
#include "FN_Basic.h"

#include "FN_AllowedToSleep_parameters.h"
#include "FN_AIModule_enums.h"
#include "FN_AIModule_structs.h"
#include "FN_AIModule_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: AllowedToSleep
*/

// BlueprintGeneratedClass /Game/AI/BehaviorTrees/Decorators/AllowedToSleep.AllowedToSleep_C
// 0x0000 (0x006C)
class UAllowedToSleep_C : public UBTDecorator_BlueprintBase
{
public:
	bool PerformConditionCheckAI(class AAIController* OwnerController, class APawn* ControlledPawn); // Function /Game/AI/BehaviorTrees/Decorators/AllowedToSleep.AllowedToSleep_C:PerformConditionCheckAI
public:
	static class UClass* StaticClass();
};

