#pragma once
#include "FN_Basic.h"

#include "FN_AbilityDecoTool_SupplyDrop_parameters.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"
#include "FN_FortniteGame_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: AbilityDecoTool_SupplyDrop
*/

// BlueprintGeneratedClass /Game/Weapons/FORT_BuildingTools/AbilityDecoTool_SupplyDrop.AbilityDecoTool_SupplyDrop_C
// 0x0008 (0x0648)
class AAbilityDecoTool_SupplyDrop_C : public AFortCustomizableAbilityDecoTool
{
public:
	FPointerToUberGraphFrame                                                                             UberGraphFrame;                                    // 0x0640 (0x0004)
	class UClass*                                                                                        NewVar_0;                                          // 0x0644 (0x0004)
public:
	void UserConstructionScript(); // Function /Game/Weapons/FORT_BuildingTools/AbilityDecoTool_SupplyDrop.AbilityDecoTool_SupplyDrop_C:UserConstructionScript
	void BPPressSecondaryFire(class AFortDecoHelper* FortDecoHelper); // Function /Game/Weapons/FORT_BuildingTools/AbilityDecoTool_SupplyDrop.AbilityDecoTool_SupplyDrop_C:BPPressSecondaryFire
	void ExecuteUbergraph_AbilityDecoTool_SupplyDrop(int32_t EntryPoint); // Function /Game/Weapons/FORT_BuildingTools/AbilityDecoTool_SupplyDrop.AbilityDecoTool_SupplyDrop_C:ExecuteUbergraph_AbilityDecoTool_SupplyDrop
public:
	static class UClass* StaticClass();
};

