#pragma once
#include "FN_Basic.h"

#include "FN_AnimNotify_PlayFeedbackLine_parameters.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_Engine_classes.h"
#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: AnimNotify_PlayFeedbackLine
*/

// BlueprintGeneratedClass /Game/Characters/Feedback/AnimNotify_PlayFeedbackLine.AnimNotify_PlayFeedbackLine_C
// 0x0011 (0x0031)
class UAnimNotify_PlayFeedbackLine_C : public UAnimNotify
{
public:
	FFortFeedbackHandle                                                                                  Event;                                             // 0x0020 (0x0010)
	bool                                                                                                 bAllowReplication;                                 // 0x0030 (0x0001)
public:
	bool Received_Notify(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation); // Function /Game/Characters/Feedback/AnimNotify_PlayFeedbackLine.AnimNotify_PlayFeedbackLine_C:Received_Notify
public:
	static class UClass* StaticClass();
};

