#pragma once
#include "FN_Basic.h"

#include "FN_B_PlayerHealthDamage_CameraLensEffect_parameters.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_Engine_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: B_PlayerHealthDamage_CameraLensEffect
*/

// BlueprintGeneratedClass /Game/Effects/Fort_Effects/Camera_Effects/B_PlayerHealthDamage_CameraLensEffect.B_PlayerHealthDamage_CameraLensEffect_C
// 0x0004 (0x02E4)
class AB_PlayerHealthDamage_CameraLensEffect_C : public AEmitterCameraLensEffectBase
{
public:
	FPointerToUberGraphFrame                                                                             UberGraphFrame;                                    // 0x02E0 (0x0004)
public:
	void UserConstructionScript(); // Function /Game/Effects/Fort_Effects/Camera_Effects/B_PlayerHealthDamage_CameraLensEffect.B_PlayerHealthDamage_CameraLensEffect_C:UserConstructionScript
	void PassParticle_Parameter(float NewParam, bool First_Hit); // Function /Game/Effects/Fort_Effects/Camera_Effects/B_PlayerHealthDamage_CameraLensEffect.B_PlayerHealthDamage_CameraLensEffect_C:PassParticle_Parameter
	void ExecuteUbergraph_B_PlayerHealthDamage_CameraLensEffect(int32_t EntryPoint); // Function /Game/Effects/Fort_Effects/Camera_Effects/B_PlayerHealthDamage_CameraLensEffect.B_PlayerHealthDamage_CameraLensEffect_C:ExecuteUbergraph_B_PlayerHealthDamage_CameraLensEffect
public:
	static class UClass* StaticClass();
};

