#pragma once
#include "FN_Basic.h"

#include "FN_ButtonStyle_RatingWidget_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: ButtonStyle_RatingWidget_Team
*/

// BlueprintGeneratedClass /Game/UI/HomeBase/Rating/ButtonStyle-RatingWidget-Team.ButtonStyle-RatingWidget-Team_C
// 0x0000 (0x15DC)
class UButtonStyle_RatingWidget_Team_C : public UButtonStyle_RatingWidget_C
{
public:
	static class UClass* StaticClass();
};

