#pragma once
#include "FN_Basic.h"

#include "FN_ButtonStyle_Base_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: ButtonStyle_Radio
*/

// BlueprintGeneratedClass /Game/UI/Buttons/Styles/ButtonStyle-Radio.ButtonStyle-Radio_C
// 0x0000 (0x15DC)
class UButtonStyle_Radio_C : public UButtonStyle_Base_C
{
public:
	static class UClass* StaticClass();
};

