#pragma once
#include "FN_Basic.h"

#include "FN_B_PlayerShieldDamage_CameraLensEffect_parameters.h"
#include "FN_B_PlayerHealthDamage_CameraLensEffect_classes.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: B_PlayerShieldDamage_CameraLensEffect
*/

// BlueprintGeneratedClass /Game/Effects/Fort_Effects/Camera_Effects/B_PlayerShieldDamage_CameraLensEffect.B_PlayerShieldDamage_CameraLensEffect_C
// 0x0004 (0x02E8)
class AB_PlayerShieldDamage_CameraLensEffect_C : public AB_PlayerHealthDamage_CameraLensEffect_C
{
public:
	FPointerToUberGraphFrame                                                                             UberGraphFrame;                                    // 0x02E4 (0x0004)
public:
	void UserConstructionScript(); // Function /Game/Effects/Fort_Effects/Camera_Effects/B_PlayerShieldDamage_CameraLensEffect.B_PlayerShieldDamage_CameraLensEffect_C:UserConstructionScript
	void PassParticle_Parameter_Shield(float NewParam); // Function /Game/Effects/Fort_Effects/Camera_Effects/B_PlayerShieldDamage_CameraLensEffect.B_PlayerShieldDamage_CameraLensEffect_C:PassParticle_Parameter_Shield
	void ExecuteUbergraph_B_PlayerShieldDamage_CameraLensEffect(int32_t EntryPoint); // Function /Game/Effects/Fort_Effects/Camera_Effects/B_PlayerShieldDamage_CameraLensEffect.B_PlayerShieldDamage_CameraLensEffect_C:ExecuteUbergraph_B_PlayerShieldDamage_CameraLensEffect
public:
	static class UClass* StaticClass();
};

