#pragma once
#include "FN_Basic.h"

#include "FN_FortniteUI_enums.h"
#include "FN_FortniteUI_structs.h"
#include "FN_FortniteUI_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: ButtonStyle_Base
*/

// BlueprintGeneratedClass /Game/UI/Buttons/Styles/ButtonStyle-Base.ButtonStyle-Base_C
// 0x0000 (0x15DC)
class UButtonStyle_Base_C : public UFortButtonStyle
{
public:
	static class UClass* StaticClass();
};

