#pragma once
#include "FN_Basic.h"

#include "FN_ButtonStyle_Default_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: ButtonStyle_Critical
*/

// BlueprintGeneratedClass /Game/UI/Buttons/Styles/ButtonStyle-Critical.ButtonStyle-Critical_C
// 0x0000 (0x15DC)
class UButtonStyle_Critical_C : public UButtonStyle_Default_C
{
public:
	static class UClass* StaticClass();
};

