#pragma once
#include "FN_Basic.h"

#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_Engine_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: B_AirstrikeCameraShake
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Generic/Gadgets/AirStrike/B_AirstrikeCameraShake.B_AirstrikeCameraShake_C
// 0x0000 (0x0120)
class UB_AirstrikeCameraShake_C : public UCameraShake
{
public:
	static class UClass* StaticClass();
};

