#pragma once
#include "FN_Basic.h"

#include "FN_B_Melee_Edged_Generic_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: B_Melee_Edged_Sword
*/

// BlueprintGeneratedClass /Game/Weapons/FORT_Melee/Blueprints/Edged/B_Melee_Edged_Sword.B_Melee_Edged_Sword_C
// 0x0000 (0x0664)
class AB_Melee_Edged_Sword_C : public AB_Melee_Edged_Generic_C
{
public:
	static class UClass* StaticClass();
};

