#pragma once
#include "FN_Basic.h"

#include "FN_B_AirStrike_Placement_parameters.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"
#include "FN_FortniteGame_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: B_AirStrike_Placement
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Generic/Gadgets/AirStrike/B_AirStrike_Placement.B_AirStrike_Placement_C
// 0x000C (0x0950)
class AB_AirStrike_Placement_C : public ABuildingProp
{
public:
	FPointerToUberGraphFrame                                                                             UberGraphFrame;                                    // 0x0944 (0x0004)
	float                                                                                                BombHeightOffset;                                  // 0x0948 (0x0004)
	class UGA_AirStrike_C*                                                                               AirStrikeAbility;                                  // 0x094C (0x0004)
public:
	void UserConstructionScript(); // Function /Game/Abilities/Player/Generic/Gadgets/AirStrike/B_AirStrike_Placement.B_AirStrike_Placement_C:UserConstructionScript
	void ReceiveBeginPlay(); // Function /Game/Abilities/Player/Generic/Gadgets/AirStrike/B_AirStrike_Placement.B_AirStrike_Placement_C:ReceiveBeginPlay
	void ExecuteUbergraph_B_AirStrike_Placement(int32_t EntryPoint); // Function /Game/Abilities/Player/Generic/Gadgets/AirStrike/B_AirStrike_Placement.B_AirStrike_Placement_C:ExecuteUbergraph_B_AirStrike_Placement
public:
	static class UClass* StaticClass();
};

