#pragma once
#include "FN_Basic.h"

#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_Engine_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: B_SupplyDropCameraShake
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Generic/Gadgets/SupplyDrop/B_SupplyDropCameraShake.B_SupplyDropCameraShake_C
// 0x0000 (0x0120)
class UB_SupplyDropCameraShake_C : public UCameraShake
{
public:
	static class UClass* StaticClass();
};

