#pragma once
#include "FN_Basic.h"

#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"
#include "FN_FortniteGame_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: CircleAroundPrimaryAssignmentGoals_Bombshell_Poison
*/

// BlueprintGeneratedClass /Game/AI/GoalSelection/GoalProviders/CircleAroundPrimaryAssignmentGoals_Bombshell_Poison.CircleAroundPrimaryAssignmentGoals_Bombshell_Poison_C
// 0x0000 (0x0070)
class UCircleAroundPrimaryAssignmentGoals_Bombshell_Poison_C : public UFortAIGoalProvider_EnvQuery
{
public:
	static class UClass* StaticClass();
};

