#pragma once
#include "FN_Basic.h"

#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"
#include "FN_FortniteGame_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: Default3PCamera
*/

// BlueprintGeneratedClass /Game/Blueprints/Camera/Original/Default3PCamera.Default3PCamera_C
// 0x0000 (0x0110)
class UDefault3PCamera_C : public UFort3PCam_Default
{
public:
	static class UClass* StaticClass();
};

