#pragma once
#include "FN_Basic.h"


/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: E_AdrenalineRushAOE
*/

// UserDefinedEnum /Game/Abilities/Player/Generic/Gadgets/AdrenalineRush/E_AdrenalineRushAOE.E_AdrenalineRushAOE
enum class E_AdrenalineRushAOE : uint8_t
{
	NewEnumerator0                                     = 0,
	NewEnumerator1                                     = 1,
	NewEnumerator2                                     = 2,
	E_MAX                                              = 3
};

