#pragma once
#include "FN_Basic.h"


/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: EngineSettings
*/

// Enum /Script/EngineSettings.EThreePlayerSplitScreenType
enum class EThreePlayerSplitScreenType : uint8_t
{
	FavorTop                                           = 0,
	FavorBottom                                        = 1,
	EThreePlayerSplitScreenType_MAX                    = 2
};

// Enum /Script/EngineSettings.ETwoPlayerSplitScreenType
enum class ETwoPlayerSplitScreenType : uint8_t
{
	Horizontal                                         = 0,
	Vertical                                           = 1,
	ETwoPlayerSplitScreenType_MAX                      = 2
};

