#pragma once
#include "FN_Basic.h"


/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: FortniteUI
*/

// Enum /Script/FortniteUI.EFortFrontEndFeatureState
enum class EFortFrontEndFeatureState : uint8_t
{
	Enabled                                            = 0,
	NoHeroes                                           = 1,
	NoRecruitableHeroes                                = 2,
	DisabledByTutorial                                 = 3,
	Invalid                                            = 4,
	EFortFrontEndFeatureState_MAX                      = 5
};

// Enum /Script/FortniteUI.EFortFrontEndFeature
enum class EFortFrontEndFeature : uint8_t
{
	ShowHomeBase                                       = 0,
	ShowHeroList                                       = 1,
	ShowVault                                          = 2,
	ShowStore                                          = 3,
	PlayZone                                           = 4,
	ShowDailyRewards                                   = 5,
	ShowHeroSelect                                     = 6,
	RecruitHero                                        = 7,
	ShowHomeBaseOverview                               = 8,
	MAX_None                                           = 9,
	EFortFrontEndFeature_MAX                           = 10
};

// Enum /Script/FortniteUI.EFortUIFeatureState
enum class EFortUIFeatureState : uint8_t
{
	Enabled                                            = 0,
	DisabledByTutorial                                 = 1,
	Invalid                                            = 2,
	EFortUIFeatureState_MAX                            = 3
};

// Enum /Script/FortniteUI.EFortUIFeature
enum class EFortUIFeature : uint8_t
{
	ShowPartyBar                                       = 0,
	ShowChatWindow                                     = 1,
	ShowFriendsMenu                                    = 2,
	MAX_None                                           = 3,
	EFortUIFeature_MAX                                 = 4
};

// Enum /Script/FortniteUI.EFlagStatus
enum class EFlagStatus : uint8_t
{
	FlagPresent                                        = 0,
	FlagNotPresent                                     = 1,
	EFlagStatus_MAX                                    = 2
};

// Enum /Script/FortniteUI.EFortDialogFeedbackType
enum class EFortDialogFeedbackType : uint8_t
{
	FriendRequestSent                                  = 0,
	FriendRequestReceived                              = 1,
	FriendRequestAccepted                              = 2,
	Default                                            = 3,
	EFortDialogFeedbackType_MAX                        = 4
};

// Enum /Script/FortniteUI.EFortDialogResult
enum class EFortDialogResult : uint8_t
{
	Confirmed                                          = 0,
	Declined                                           = 1,
	Ignored                                            = 2,
	Killed                                             = 3,
	TimedOut                                           = 4,
	Unknown                                            = 5,
	EFortDialogResult_MAX                              = 6
};

// Enum /Script/FortniteUI.EFortHitPointModificationReason
enum class EFortHitPointModificationReason : uint8_t
{
	Invalid                                            = 0,
	InitalSet                                          = 1,
	AutoRegen                                          = 2,
	ItemRegen                                          = 3,
	DamageOverTime                                     = 4,
	DamageReceived                                     = 5,
	EFortHitPointModificationReason_MAX                = 6
};

// Enum /Script/FortniteUI.EFortBuildingInteraction
enum class EFortBuildingInteraction : uint8_t
{
	None                                               = 0,
	Build                                              = 1,
	Repair                                             = 2,
	Upgrade                                            = 3,
	Edit                                               = 4,
	BeingModified                                      = 5,
	ConfirmEdit                                        = 6,
	EFortBuildingInteraction_MAX                       = 7
};

// Enum /Script/FortniteUI.EFortBuildingHealthDisplayRule
enum class EFortBuildingHealthDisplayRule : uint8_t
{
	Never                                              = 0,
	Allowed                                            = 1,
	Always                                             = 2,
	EFortBuildingHealthDisplayRule_MAX                 = 3
};

// Enum /Script/FortniteUI.EFortStoreState
enum class EFortStoreState : uint8_t
{
	Error                                              = 0,
	WaitingForResponse                                 = 1,
	Closed                                             = 2,
	CardPackStore                                      = 3,
	CurrencyStore                                      = 4,
	WebPayment                                         = 5,
	PackOpen                                           = 6,
	CardEnter                                          = 7,
	CardBackReveal                                     = 8,
	CardFlip                                           = 9,
	CardFrontReveal                                    = 10,
	CardExit                                           = 11,
	SummaryAdd                                         = 12,
	PackDestroy                                        = 13,
	Summary                                            = 14,
	MAX_None                                           = 15,
	EFortStoreState_MAX                                = 16
};

// Enum /Script/FortniteUI.EFortTutorialGlowType
enum class EFortTutorialGlowType : uint8_t
{
	None                                               = 0,
	Look                                               = 1,
	Click                                              = 2,
	EFortTutorialGlowType_MAX                          = 3
};

// Enum /Script/FortniteUI.EFortBangSize
enum class EFortBangSize : uint8_t
{
	XXS                                                = 0,
	XS                                                 = 1,
	S                                                  = 2,
	M                                                  = 3,
	L                                                  = 4,
	XL                                                 = 5,
	EFortBangSize_MAX                                  = 6
};

// Enum /Script/FortniteUI.EFortUIState
enum class EFortUIState : uint8_t
{
	Invalid                                            = 0,
	Login                                              = 1,
	JoinServer                                         = 2,
	FrontEnd                                           = 3,
	PvE_PostGame                                       = 4,
	PvP_PostGame                                       = 5,
	InGame                                             = 6,
	Cinematic                                          = 7,
	MAX                                                = 8,
	EFortUIState_MAX                                   = 9
};

// Enum /Script/FortniteUI.EGridSortKind
enum class EGridSortKind : uint8_t
{
	None                                               = 0,
	ByNumber                                           = 1,
	ByString                                           = 2,
	ByNumberThenString                                 = 3,
	ByStringThenNumber                                 = 4,
	EGridSortKind_MAX                                  = 5
};

// Enum /Script/FortniteUI.EButtonGroupDirection
enum class EButtonGroupDirection : uint8_t
{
	Horizontal                                         = 0,
	Vertical                                           = 1,
	EButtonGroupDirection_MAX                          = 2
};

// Enum /Script/FortniteUI.EFortSocialPanelTab
enum class EFortSocialPanelTab : uint8_t
{
	PartyInvitations                                   = 0,
	Friends                                            = 1,
	RecentPlayers                                      = 2,
	Max                                                = 3,
	EFortSocialPanelTab_MAX                            = 4
};

// Enum /Script/FortniteUI.EFortSocialPanelType
enum class EFortSocialPanelType : uint8_t
{
	Join                                               = 0,
	Invite                                             = 1,
	Max                                                = 2,
	EFortSocialPanelType_MAX                           = 3
};

// Enum /Script/FortniteUI.EModalContainerSize
enum class EModalContainerSize : uint8_t
{
	ExtraSmall                                         = 0,
	Small                                              = 1,
	Medium                                             = 2,
	Large                                              = 3,
	Max                                                = 4,
	EModalContainerSize_MAX                            = 5
};

// Enum /Script/FortniteUI.ENotificationType
enum class ENotificationType : uint8_t
{
	Basic                                              = 0,
	Friends                                            = 1,
	ENotificationType_MAX                              = 2
};

// Enum /Script/FortniteUI.ENotificationResult
enum class ENotificationResult : uint8_t
{
	Confirmed                                          = 0,
	Declined                                           = 1,
	Unknown                                            = 2,
	ENotificationResult_MAX                            = 3
};

// Enum /Script/FortniteUI.EFortInventoryContext
enum class EFortInventoryContext : uint8_t
{
	Game                                               = 0,
	Lobby                                              = 1,
	FrontEnd                                           = 2,
	Pickup                                             = 3,
	EFortInventoryContext_MAX                          = 4
};

// Enum /Script/FortniteUI.ENameStatus
enum class ENameStatus : uint8_t
{
	Valid                                              = 0,
	TooShort                                           = 1,
	TooLong                                            = 2,
	ContainsInvalidCharacter                           = 3,
	ENameStatus_MAX                                    = 4
};

// Enum /Script/FortniteUI.EFortLegacySlateWidget
enum class EFortLegacySlateWidget : uint8_t
{
	None                                               = 0,
	Options                                            = 1,
	FriendsList                                        = 2,
	Feedback                                           = 3,
	Minimap                                            = 4,
	DefaultObjective                                   = 5,
	Mission                                            = 6,
	Chat                                               = 7,
	HUDContextInfo                                     = 8,
	CenterPopupMessage                                 = 9,
	PinnedSchematics                                   = 10,
	Results                                            = 11,
	CraftingInfo                                       = 12,
	ClientNotification                                 = 13,
	MAX                                                = 14,
	EFortLegacySlateWidget_MAX                         = 15
};

// Enum /Script/FortniteUI.EModalContainerSlot
enum class EModalContainerSlot : uint8_t
{
	Top                                                = 0,
	Middle                                             = 1,
	Bottom                                             = 2,
	Background                                         = 3,
	Max                                                = 4,
	EModalContainerSlot_MAX                            = 5
};

// Enum /Script/FortniteUI.EPauseType
enum class EPauseType : uint8_t
{
	NoPause                                            = 0,
	Rare                                               = 1,
	New                                                = 2,
	NewAndRare                                         = 3,
	EPauseType_MAX                                     = 4
};

// Enum /Script/FortniteUI.ECardPackPurchaseError
enum class ECardPackPurchaseError : uint8_t
{
	PendingServerConfirmation                          = 0,
	NotEnoughMtx                                       = 1,
	NoneLeft                                           = 2,
	PurchaseAlreadyPending                             = 3,
	NoConnection                                       = 4,
	ECardPackPurchaseError_MAX                         = 5
};

// Enum /Script/FortniteUI.EFortStoreTransition
enum class EFortStoreTransition : uint8_t
{
	X                                                  = 0,
	EFortStoreTransition_MAX                           = 1
};

// Enum /Script/FortniteUI.EFortButtonState
enum class EFortButtonState : uint8_t
{
	Up                                                 = 0,
	Over                                               = 1,
	Down                                               = 2,
	Release                                            = 3,
	Out                                                = 4,
	Disabled                                           = 5,
	KB_Down                                            = 6,
	KB_Release                                         = 7,
	Max                                                = 8,
	EFortButtonState_MAX                               = 9
};

// Enum /Script/FortniteUI.EPageDirection
enum class EPageDirection : uint8_t
{
	Page_Left                                          = 0,
	Page_Right                                         = 1,
	Page_MAX                                           = 2
};

// Enum /Script/FortniteUI.EUILoginStatus
enum class EUILoginStatus : uint8_t
{
	Invalid                                            = 0,
	LoggedOut                                          = 1,
	LoggingIn                                          = 2,
	LoginFailed                                        = 3,
	LoginSuccess                                       = 4,
	EUILoginStatus_MAX                                 = 5
};

// Enum /Script/FortniteUI.EVaultCommandType
enum class EVaultCommandType : uint8_t
{
	Upgrade                                            = 0,
	Customize                                          = 1,
	Recycle                                            = 2,
	Retire                                             = 3,
	Boost                                              = 4,
	EVaultCommandType_MAX                              = 5
};

// Enum /Script/FortniteUI.EVaultContentSortType
enum class EVaultContentSortType : uint8_t
{
	ByName                                             = 0,
	ByCraftingTier                                     = 1,
	ByLevel                                            = 2,
	ByCategory                                         = 3,
	ByRarity                                           = 4,
	ByType                                             = 5,
	ByLocation                                         = 6,
	ByPersonality                                      = 7,
	ByBonus                                            = 8,
	EVaultContentSortType_MAX                          = 9
};

// Enum /Script/FortniteUI.EVaultContentType
enum class EVaultContentType : uint8_t
{
	Heroes                                             = 0,
	Schematics                                         = 1,
	Personnel                                          = 2,
	Misc                                               = 3,
	EVaultContentType_MAX                              = 4
};

