#pragma once
#include "FN_Basic.h"


/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: Foliage
*/

// Enum /Script/Foliage.EFoliageScaling
enum class EFoliageScaling : uint8_t
{
	Uniform                                            = 0,
	Free                                               = 1,
	LockXY                                             = 2,
	LockXZ                                             = 3,
	LockYZ                                             = 4,
	EFoliageScaling_MAX                                = 5
};

// Enum /Script/Foliage.FoliageVertexColorMask
enum class FoliageVertexColorMask : uint8_t
{
	FOLIAGEVERTEXCOLORMASK_Disabled                    = 0,
	FOLIAGEVERTEXCOLORMASK_Red                         = 1,
	FOLIAGEVERTEXCOLORMASK_Green                       = 2,
	FOLIAGEVERTEXCOLORMASK_Blue                        = 3,
	FOLIAGEVERTEXCOLORMASK_Alpha                       = 4,
	FOLIAGEVERTEXCOLORMASK_MAX                         = 5
};

// Enum /Script/Foliage.ESimulationQuery
enum class ESimulationQuery : uint8_t
{
	CollisionOverlap                                   = 0,
	ShadeOverlap                                       = 1,
	AnyOverlap                                         = 2,
	ESimulationQuery_MAX                               = 3
};

// Enum /Script/Foliage.ESimulationOverlap
enum class ESimulationOverlap : uint8_t
{
	CollisionOverlap                                   = 0,
	ShadeOverlap                                       = 1,
	None                                               = 2,
	ESimulationOverlap_MAX                             = 3
};

