#pragma once
#include "FN_Basic.h"

#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"
#include "FN_FortniteGame_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: FeedbackAnnouncer
*/

// BlueprintGeneratedClass /Game/Characters/Feedback/FeedbackAnnouncer.FeedbackAnnouncer_C
// 0x0000 (0x0860)
class AFeedbackAnnouncer_C : public AFortPawn_FeedbackAnnouncer
{
public:
	static class UClass* StaticClass();
};

