#pragma once
#include "FN_Basic.h"

#include "FN_GAB_HuskBaseRadialMelee_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GAB_HuskLobberRadialMelee
*/

// BlueprintGeneratedClass /Game/Abilities/NPC/Husk/Lobber/GAB_HuskLobberRadialMelee.GAB_HuskLobberRadialMelee_C
// 0x0000 (0x06E9)
class UGAB_HuskLobberRadialMelee_C : public UGAB_HuskBaseRadialMelee_C
{
public:
	static class UClass* StaticClass();
};

