#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Constructor_SubroutineOptimizationApplied
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Constructor/Traits/EnergyFabrication/GE_Constructor_SubroutineOptimizationApplied.GE_Constructor_SubroutineOptimizationApplied_C
// 0x0000 (0x0368)
class UGE_Constructor_SubroutineOptimizationApplied_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

