#pragma once
#include "FN_Basic.h"

#include "FN_GET_DirectEnergyDamage_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Constructor_PlasmaPulseDamage
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Constructor/Gadgets/PlasmaPulse/GE_Constructor_PlasmaPulseDamage.GE_Constructor_PlasmaPulseDamage_C
// 0x0000 (0x0368)
class UGE_Constructor_PlasmaPulseDamage_C : public UGET_DirectEnergyDamage_C
{
public:
	static class UClass* StaticClass();
};

