#pragma once
#include "FN_Basic.h"

#include "FN_GET_Cooldown_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Generic_BannerCooldown
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Generic/Gadgets/Banner/GE_Generic_BannerCooldown.GE_Generic_BannerCooldown_C
// 0x0000 (0x0368)
class UGE_Generic_BannerCooldown_C : public UGET_Cooldown_C
{
public:
	static class UClass* StaticClass();
};

