#pragma once
#include "FN_Basic.h"

#include "FN_GET_DirectBluntDamage_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Constructor_RiotShieldDamage
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Constructor/Gadgets/BullRush/GE_Constructor_RiotShieldDamage.GE_Constructor_RiotShieldDamage_C
// 0x0000 (0x0368)
class UGE_Constructor_RiotShieldDamage_C : public UGET_DirectBluntDamage_C
{
public:
	static class UClass* StaticClass();
};

