#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Commando_CommandoTraining3
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Commando/Packages/GE_Commando_CommandoTraining3.GE_Commando_CommandoTraining3_C
// 0x0000 (0x0368)
class UGE_Commando_CommandoTraining3_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

