#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Map_Constructor_Vitality_Health
*/

// BlueprintGeneratedClass /Game/Balance/CombinedStats/Constructor/MappedEffects/GE_Map_Constructor_Vitality_Health.GE_Map_Constructor_Vitality_Health_C
// 0x0000 (0x0368)
class UGE_Map_Constructor_Vitality_Health_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

