#pragma once
#include "FN_Basic.h"

#include "FN_GET_TagContainer_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Outlander_FastGravity
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Outlander/Traits/Gravitas/GE_Outlander_FastGravity.GE_Outlander_FastGravity_C
// 0x0000 (0x0368)
class UGE_Outlander_FastGravity_C : public UGET_TagContainer_C
{
public:
	static class UClass* StaticClass();
};

