#pragma once
#include "FN_Basic.h"

#include "FN_GAB_HuskTurnTransition_parameters.h"
#include "FN_CoreUObject_enums.h"
#include "FN_CoreUObject_structs.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"
#include "FN_FortniteGame_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GAB_HuskTurnTransition
*/

// BlueprintGeneratedClass /Game/Abilities/NPC/Husk/Base/GAB_HuskTurnTransition.GAB_HuskTurnTransition_C
// 0x0010 (0x0708)
class UGAB_HuskTurnTransition_C : public UFortGameplayAbility_AITurnTransition
{
public:
	FPointerToUberGraphFrame                                                                             UberGraphFrame;                                    // 0x06F8 (0x0004)
	FRotator                                                                                             PriorPawnRotationRate;                             // 0x06FC (0x000C)
public:
	void OnCancelled_B51702764205E90DF617B6BDB1285CFF(); // Function /Game/Abilities/NPC/Husk/Base/GAB_HuskTurnTransition.GAB_HuskTurnTransition_C:OnCancelled_B51702764205E90DF617B6BDB1285CFF
	void OnInterrupted_B51702764205E90DF617B6BDB1285CFF(); // Function /Game/Abilities/NPC/Husk/Base/GAB_HuskTurnTransition.GAB_HuskTurnTransition_C:OnInterrupted_B51702764205E90DF617B6BDB1285CFF
	void OnComplete_B51702764205E90DF617B6BDB1285CFF(); // Function /Game/Abilities/NPC/Husk/Base/GAB_HuskTurnTransition.GAB_HuskTurnTransition_C:OnComplete_B51702764205E90DF617B6BDB1285CFF
	void K2_ActivateAbility(); // Function /Game/Abilities/NPC/Husk/Base/GAB_HuskTurnTransition.GAB_HuskTurnTransition_C:K2_ActivateAbility
	void ExecuteUbergraph_GAB_HuskTurnTransition(int32_t EntryPoint); // Function /Game/Abilities/NPC/Husk/Base/GAB_HuskTurnTransition.GAB_HuskTurnTransition_C:ExecuteUbergraph_GAB_HuskTurnTransition
public:
	static class UClass* StaticClass();
};

