#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Outlander_CastTheFirstStone
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Outlander/Traits/ZonedOut/GE_Outlander_CastTheFirstStone.GE_Outlander_CastTheFirstStone_C
// 0x0000 (0x0368)
class UGE_Outlander_CastTheFirstStone_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

