#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Ninja_NinjaTraining1
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Ninja/Packages/GE_Ninja_NinjaTraining1.GE_Ninja_NinjaTraining1_C
// 0x0000 (0x0368)
class UGE_Ninja_NinjaTraining1_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

