#pragma once
#include "FN_Basic.h"

#include "FN_GET_FatiguedParent_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Constructor_TriggeredFatigue
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Constructor/Packages/GE_Constructor_TriggeredFatigue.GE_Constructor_TriggeredFatigue_C
// 0x0000 (0x0368)
class UGE_Constructor_TriggeredFatigue_C : public UGET_FatiguedParent_C
{
public:
	static class UClass* StaticClass();
};

