#pragma once
#include "FN_Basic.h"

#include "FN_GET_TagContainer_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Constructor_CardioFeedbackLoop
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Constructor/Traits/Territorial/GE_Constructor_CardioFeedbackLoop.GE_Constructor_CardioFeedbackLoop_C
// 0x0000 (0x0368)
class UGE_Constructor_CardioFeedbackLoop_C : public UGET_TagContainer_C
{
public:
	static class UClass* StaticClass();
};

