#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Consumable_Heal
*/

// BlueprintGeneratedClass /Game/Loot/Consumables/GameplayEffects/GE_Consumable_Heal.GE_Consumable_Heal_C
// 0x0000 (0x0368)
class UGE_Consumable_Heal_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

