#pragma once
#include "FN_Basic.h"

#include "FN_GAB_GenericStunned_parameters.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"
#include "FN_FortniteGame_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GAB_GenericStunned
*/

// GameplayAbilityBlueprintGeneratedClass /Game/Abilities/NPC/Generic/GAB_GenericStunned.GAB_GenericStunned_C
// 0x0004 (0x06E0)
class UGAB_GenericStunned_C : public UFortGameplayAbility
{
public:
	FPointerToUberGraphFrame                                                                             UberGraphFrame;                                    // 0x06DC (0x0004)
public:
	void K2_OnEndAbility(); // Function /Game/Abilities/NPC/Generic/GAB_GenericStunned.GAB_GenericStunned_C:K2_OnEndAbility
	void K2_ActivateAbility(); // Function /Game/Abilities/NPC/Generic/GAB_GenericStunned.GAB_GenericStunned_C:K2_ActivateAbility
	void ExecuteUbergraph_GAB_GenericStunned(int32_t EntryPoint); // Function /Game/Abilities/NPC/Generic/GAB_GenericStunned.GAB_GenericStunned_C:ExecuteUbergraph_GAB_GenericStunned
public:
	static class UClass* StaticClass();
};

