#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Commando_PerfectEngineering
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Commando/Traits/Explosives/GE_Commando_PerfectEngineering.GE_Commando_PerfectEngineering_C
// 0x0000 (0x0368)
class UGE_Commando_PerfectEngineering_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

