#pragma once
#include "FN_Basic.h"

#include "FN_GET_Cooldown_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_AirStrike_Cooldown
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Generic/Gadgets/AirStrike/GE_AirStrike_Cooldown.GE_AirStrike_Cooldown_C
// 0x0000 (0x0368)
class UGE_AirStrike_Cooldown_C : public UGET_Cooldown_C
{
public:
	static class UClass* StaticClass();
};

