#pragma once
#include "FN_Basic.h"

#include "FN_GET_DirectEnergyDamage_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Constructor_KineticOverloadDamageSlowTrigger
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Constructor/Traits/AppliedForce/GE_Constructor_KineticOverloadDamageSlowTrigger.GE_Constructor_KineticOverloadDamageSlowTrigger_C
// 0x0000 (0x0368)
class UGE_Constructor_KineticOverloadDamageSlowTrigger_C : public UGET_DirectEnergyDamage_C
{
public:
	static class UClass* StaticClass();
};

