#pragma once
#include "FN_Basic.h"


/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GameSubCatalog
*/

// Enum /Script/GameSubCatalog.EAppStore
enum class EAppStore : uint8_t
{
	DebugStore                                         = 0,
	EpicPurchasingService                              = 1,
	IOSAppStore                                        = 2,
	WeChatAppStore                                     = 3,
	GooglePlayAppStore                                 = 4,
	KindleStore                                        = 5,
	PlayStationStore                                   = 6,
	XboxLiveStore                                      = 7,
	MAX                                                = 8,
	EAppStore_MAX                                      = 9
};

// Enum /Script/GameSubCatalog.EStoreCurrencyType
enum class EStoreCurrencyType : uint8_t
{
	RealMoney                                          = 0,
	MtxCurrency                                        = 1,
	GameItem                                           = 2,
	Other                                              = 3,
	MAX                                                = 4,
	EStoreCurrencyType_MAX                             = 5
};

