#pragma once
#include "FN_Basic.h"

#include "FN_Get_DirectDamageParent_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_ReflectedDamage
*/

// BlueprintGeneratedClass /Game/GameplayEffectTemplates/GE_ReflectedDamage.GE_ReflectedDamage_C
// 0x0000 (0x0368)
class UGE_ReflectedDamage_C : public UGet_DirectDamageParent_C
{
public:
	static class UClass* StaticClass();
};

