#pragma once
#include "FN_Basic.h"

#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"
#include "FN_FortniteGame_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GCNS_Commando_IfItBleedsTick
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Commando/Traits/Commando/GCNS_Commando_IfItBleedsTick.GCNS_Commando_IfItBleedsTick_C
// 0x0000 (0x0044)
class UGCNS_Commando_IfItBleedsTick_C : public UFortGameplayCueNotify_Simple
{
public:
	static class UClass* StaticClass();
};

