#pragma once
#include "FN_Basic.h"

#include "FN_GAB_HuskHuntingSearch_parameters.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"
#include "FN_FortniteGame_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GAB_HuskHuntingSearch
*/

// GameplayAbilityBlueprintGeneratedClass /Game/Abilities/NPC/Husk/Base/GAB_HuskHuntingSearch.GAB_HuskHuntingSearch_C
// 0x0004 (0x06E0)
class UGAB_HuskHuntingSearch_C : public UFortGameplayAbility
{
public:
	FPointerToUberGraphFrame                                                                             UberGraphFrame;                                    // 0x06DC (0x0004)
public:
	void Completed_9925B44A484135CDB5C78BAF8BED9454(FGameplayAbilityTargetDataHandle TargetData, FGameplayTag ApplicationTag); // Function /Game/Abilities/NPC/Husk/Base/GAB_HuskHuntingSearch.GAB_HuskHuntingSearch_C:Completed_9925B44A484135CDB5C78BAF8BED9454
	void Cancelled_9925B44A484135CDB5C78BAF8BED9454(FGameplayAbilityTargetDataHandle TargetData, FGameplayTag ApplicationTag); // Function /Game/Abilities/NPC/Husk/Base/GAB_HuskHuntingSearch.GAB_HuskHuntingSearch_C:Cancelled_9925B44A484135CDB5C78BAF8BED9454
	void Triggered_9925B44A484135CDB5C78BAF8BED9454(FGameplayAbilityTargetDataHandle TargetData, FGameplayTag ApplicationTag); // Function /Game/Abilities/NPC/Husk/Base/GAB_HuskHuntingSearch.GAB_HuskHuntingSearch_C:Triggered_9925B44A484135CDB5C78BAF8BED9454
	void K2_ActivateAbility(); // Function /Game/Abilities/NPC/Husk/Base/GAB_HuskHuntingSearch.GAB_HuskHuntingSearch_C:K2_ActivateAbility
	void ExecuteUbergraph_GAB_HuskHuntingSearch(int32_t EntryPoint); // Function /Game/Abilities/NPC/Husk/Base/GAB_HuskHuntingSearch.GAB_HuskHuntingSearch_C:ExecuteUbergraph_GAB_HuskHuntingSearch
public:
	static class UClass* StaticClass();
};

