#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Map_Commando_Defense_ShieldStrength_ShieldRegen
*/

// BlueprintGeneratedClass /Game/Balance/CombinedStats/Commando/MappedEffects/GE_Map_Commando_Defense_ShieldStrength_ShieldRegen.GE_Map_Commando_Defense_ShieldStrength_ShieldRegen_C
// 0x0000 (0x0368)
class UGE_Map_Commando_Defense_ShieldStrength_ShieldRegen_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

