#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_HuskAOE4RemovePoison
*/

// BlueprintGeneratedClass /Game/Abilities/NPC/Husk/Base/GE_HuskAOE4RemovePoison.GE_HuskAOE4RemovePoison_C
// 0x0000 (0x0368)
class UGE_HuskAOE4RemovePoison_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

