#pragma once
#include "FN_Basic.h"

#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GAT_ConstructorTriggeredAbility
*/

