#pragma once
#include "FN_Basic.h"

#include "FN_GET_DirectCreatureDamage_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_HuskAOE1TouchDamagePoison
*/

// BlueprintGeneratedClass /Game/Abilities/NPC/Husk/Base/GE_HuskAOE1TouchDamagePoison.GE_HuskAOE1TouchDamagePoison_C
// 0x0000 (0x0368)
class UGE_HuskAOE1TouchDamagePoison_C : public UGET_DirectCreatureDamage_C
{
public:
	static class UClass* StaticClass();
};

