#pragma once
#include "FN_Basic.h"

#include "FN_GA_Ninja_WeaponSwitch_parameters.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"
#include "FN_FortniteGame_classes.h"
#include "FN_GameplayTags_enums.h"
#include "FN_GameplayTags_structs.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GA_Ninja_WeaponSwitch
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Ninja/Traits/Shinobi/GA_Ninja_WeaponSwitch.GA_Ninja_WeaponSwitch_C
// 0x0034 (0x0710)
class UGA_Ninja_WeaponSwitch_C : public UFortGameplayAbility
{
public:
	FPointerToUberGraphFrame                                                                             UberGraphFrame;                                    // 0x06DC (0x0004)
	FGameplayTagContainer                                                                                TC_IsEdged;                                        // 0x06E0 (0x0018)
	FGameplayTagContainer                                                                                TC_IsAssassinate;                                  // 0x06F8 (0x0018)
public:
	void K2_ActivateAbilityFromEvent(FGameplayEventData EventData); // Function /Game/Abilities/Player/Ninja/Traits/Shinobi/GA_Ninja_WeaponSwitch.GA_Ninja_WeaponSwitch_C:K2_ActivateAbilityFromEvent
	void ExecuteUbergraph_GA_Ninja_WeaponSwitch(int32_t EntryPoint); // Function /Game/Abilities/Player/Ninja/Traits/Shinobi/GA_Ninja_WeaponSwitch.GA_Ninja_WeaponSwitch_C:ExecuteUbergraph_GA_Ninja_WeaponSwitch
public:
	static class UClass* StaticClass();
};

