#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Ninja_TrainedThrow
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Ninja/Traits/WayOfTheStar/GE_Ninja_TrainedThrow.GE_Ninja_TrainedThrow_C
// 0x0000 (0x0368)
class UGE_Ninja_TrainedThrow_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

