#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Ninja_MantisLand
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Ninja/Traits/WayOfTheShadow/GE_Ninja_MantisLand.GE_Ninja_MantisLand_C
// 0x0000 (0x0368)
class UGE_Ninja_MantisLand_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

