#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Constructor_BASEDefault
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Constructor/Gadgets/BASE/GE_Constructor_BASEDefault.GE_Constructor_BASEDefault_C
// 0x0000 (0x0368)
class UGE_Constructor_BASEDefault_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

