#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_BiometricResonenceAppliedHeal
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Constructor/Traits/Shielding/GE_BiometricResonenceAppliedHeal.GE_BiometricResonenceAppliedHeal_C
// 0x0000 (0x0368)
class UGE_BiometricResonenceAppliedHeal_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

