#pragma once
#include "FN_Basic.h"

#include "FN_GadgetSelectTile_parameters.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_FortniteUI_enums.h"
#include "FN_FortniteUI_structs.h"
#include "FN_FortniteUI_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GadgetSelectTile
*/

// WidgetBlueprintGeneratedClass /Game/UI/HeroSelect/GadgetSelectTile.GadgetSelectTile_C
// 0x0008 (0x0254)
class UGadgetSelectTile_C : public UFortGridPickerTile
{
public:
	FPointerToUberGraphFrame                                                                             UberGraphFrame;                                    // 0x024C (0x0004)
	class UItem_C*                                                                                       Item;                                              // 0x0250 (0x0004)
public:
	void SetData(class UObject* InData); // Function /Game/UI/HeroSelect/GadgetSelectTile.GadgetSelectTile_C:SetData
	void BndEvt__Item_K2Node_ComponentBoundEvent_357_FortBaseButtonClicked__DelegateSignature(class UFortBaseButton* Button); // Function /Game/UI/HeroSelect/GadgetSelectTile.GadgetSelectTile_C:BndEvt__Item_K2Node_ComponentBoundEvent_357_FortBaseButtonClicked__DelegateSignature
	void ExecuteUbergraph_GadgetSelectTile(int32_t EntryPoint); // Function /Game/UI/HeroSelect/GadgetSelectTile.GadgetSelectTile_C:ExecuteUbergraph_GadgetSelectTile
public:
	static class UClass* StaticClass();
};

// LinkerPlaceholderClass /Game/UI/HeroSelect/GadgetSelectTile.PLACEHOLDER-CLASS__Item_C_155
// 0x0000 (0x0000)
class PLACEHOLDER_CLASS__Item_C_155
{
public:
	static class UClass* StaticClass();
};

