#pragma once
#include "FN_Basic.h"

#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"
#include "FN_FortniteGame_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GCNS_Constructor_ElectrifiedFloors
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Constructor/Gadgets/BASE/GCNS_Constructor_ElectrifiedFloors.GCNS_Constructor_ElectrifiedFloors_C
// 0x0000 (0x0044)
class UGCNS_Constructor_ElectrifiedFloors_C : public UFortGameplayCueNotify_Simple
{
public:
	static class UClass* StaticClass();
};

