#pragma once
#include "FN_Basic.h"

#include "FN_GA_Generic_ProximityMineExplosion_parameters.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"
#include "FN_FortniteGame_classes.h"
#include "FN_GameplayTags_enums.h"
#include "FN_GameplayTags_structs.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GA_Generic_ProximityMineExplosion
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Generic/Gadgets/Proximity_Mines/GA_Generic_ProximityMineExplosion.GA_Generic_ProximityMineExplosion_C
// 0x000C (0x06E8)
class UGA_Generic_ProximityMineExplosion_C : public UFortGameplayAbility
{
public:
	FPointerToUberGraphFrame                                                                             UberGraphFrame;                                    // 0x06DC (0x0004)
	FGameplayTag                                                                                         EC_Explosion;                                      // 0x06E0 (0x0008)
public:
	void Cancelled_8BEAB59F4207CD7783898D81D6492C18(FGameplayAbilityTargetDataHandle TargetData, FGameplayTag ApplicationTag); // Function /Game/Abilities/Player/Generic/Gadgets/Proximity_Mines/GA_Generic_ProximityMineExplosion.GA_Generic_ProximityMineExplosion_C:Cancelled_8BEAB59F4207CD7783898D81D6492C18
	void Targeted_8BEAB59F4207CD7783898D81D6492C18(FGameplayAbilityTargetDataHandle TargetData, FGameplayTag ApplicationTag); // Function /Game/Abilities/Player/Generic/Gadgets/Proximity_Mines/GA_Generic_ProximityMineExplosion.GA_Generic_ProximityMineExplosion_C:Targeted_8BEAB59F4207CD7783898D81D6492C18
	void K2_ActivateAbilityFromEvent(FGameplayEventData EventData); // Function /Game/Abilities/Player/Generic/Gadgets/Proximity_Mines/GA_Generic_ProximityMineExplosion.GA_Generic_ProximityMineExplosion_C:K2_ActivateAbilityFromEvent
	void ExecuteUbergraph_GA_Generic_ProximityMineExplosion(int32_t EntryPoint); // Function /Game/Abilities/Player/Generic/Gadgets/Proximity_Mines/GA_Generic_ProximityMineExplosion.GA_Generic_ProximityMineExplosion_C:ExecuteUbergraph_GA_Generic_ProximityMineExplosion
public:
	static class UClass* StaticClass();
};

