#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GET_Cooldown
*/

// BlueprintGeneratedClass /Game/GameplayEffectTemplates/GET_Cooldown.GET_Cooldown_C
// 0x0000 (0x0368)
class UGET_Cooldown_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

