#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Outlander_OutlanderTraining4
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Outlander/Packages/GE_Outlander_OutlanderTraining4.GE_Outlander_OutlanderTraining4_C
// 0x0000 (0x0368)
class UGE_Outlander_OutlanderTraining4_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

