#pragma once
#include "FN_Basic.h"

#include "FN_GA_Trap_FloorJumpPadDirectional_parameters.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_GA_TrapGeneric_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GA_Trap_FloorJumpPadDirectional
*/

// BlueprintGeneratedClass /Game/Abilities/Traps/FloorJumpPadDirectional/GA_Trap_FloorJumpPadDirectional.GA_Trap_FloorJumpPadDirectional_C
// 0x000C (0x0700)
class UGA_Trap_FloorJumpPadDirectional_C : public UGA_TrapGeneric_C
{
public:
	FPointerToUberGraphFrame                                                                             UberGraphFrame;                                    // 0x06F4 (0x0004)
	float                                                                                                LaunchPitch;                                       // 0x06F8 (0x0004)
	float                                                                                                LaunchStrength;                                    // 0x06FC (0x0004)
public:
	void K2_ActivateAbility(); // Function /Game/Abilities/Traps/FloorJumpPadDirectional/GA_Trap_FloorJumpPadDirectional.GA_Trap_FloorJumpPadDirectional_C:K2_ActivateAbility
	void ExecuteUbergraph_GA_Trap_FloorJumpPadDirectional(int32_t EntryPoint); // Function /Game/Abilities/Traps/FloorJumpPadDirectional/GA_Trap_FloorJumpPadDirectional.GA_Trap_FloorJumpPadDirectional_C:ExecuteUbergraph_GA_Trap_FloorJumpPadDirectional
public:
	static class UClass* StaticClass();
};

