#pragma once
#include "FN_Basic.h"

#include "FN_GAB_HuskyHuskMelee_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GAB_BlasterMelee
*/

// GameplayAbilityBlueprintGeneratedClass /Game/Abilities/NPC/Blaster/GAB_BlasterMelee.GAB_BlasterMelee_C
// 0x0000 (0x06EC)
class UGAB_BlasterMelee_C : public UGAB_HuskyHuskMelee_C
{
public:
	static class UClass* StaticClass();
};

