#pragma once
#include "FN_Basic.h"

#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"
#include "FN_FortniteGame_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GCN_NPC_Fire
*/

// BlueprintGeneratedClass /Game/Abilities/NPC/Elemental/GCN_NPC_Fire.GCN_NPC_Fire_C
// 0x0000 (0x02AC)
class AGCN_NPC_Fire_C : public AFortGameplayCueNotify_Looping
{
public:
	static class UClass* StaticClass();
};

