#pragma once
#include "FN_Basic.h"

#include "FN_GAB_HuskFrustration_parameters.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"
#include "FN_FortniteGame_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GAB_HuskFrustration
*/

// GameplayAbilityBlueprintGeneratedClass /Game/Abilities/NPC/Husk/Base/GAB_HuskFrustration.GAB_HuskFrustration_C
// 0x0004 (0x06E0)
class UGAB_HuskFrustration_C : public UFortGameplayAbility
{
public:
	FPointerToUberGraphFrame                                                                             UberGraphFrame;                                    // 0x06DC (0x0004)
public:
	void Completed_4426349D48BB9D962857A490453AEC50(FGameplayAbilityTargetDataHandle TargetData, FGameplayTag ApplicationTag); // Function /Game/Abilities/NPC/Husk/Base/GAB_HuskFrustration.GAB_HuskFrustration_C:Completed_4426349D48BB9D962857A490453AEC50
	void Cancelled_4426349D48BB9D962857A490453AEC50(FGameplayAbilityTargetDataHandle TargetData, FGameplayTag ApplicationTag); // Function /Game/Abilities/NPC/Husk/Base/GAB_HuskFrustration.GAB_HuskFrustration_C:Cancelled_4426349D48BB9D962857A490453AEC50
	void Triggered_4426349D48BB9D962857A490453AEC50(FGameplayAbilityTargetDataHandle TargetData, FGameplayTag ApplicationTag); // Function /Game/Abilities/NPC/Husk/Base/GAB_HuskFrustration.GAB_HuskFrustration_C:Triggered_4426349D48BB9D962857A490453AEC50
	void K2_ActivateAbility(); // Function /Game/Abilities/NPC/Husk/Base/GAB_HuskFrustration.GAB_HuskFrustration_C:K2_ActivateAbility
	void ExecuteUbergraph_GAB_HuskFrustration(int32_t EntryPoint); // Function /Game/Abilities/NPC/Husk/Base/GAB_HuskFrustration.GAB_HuskFrustration_C:ExecuteUbergraph_GAB_HuskFrustration
public:
	static class UClass* StaticClass();
};

