#pragma once
#include "FN_Basic.h"

#include "FN_GAB_HuskyHuskCeilingMelee_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GAB_BlasterCeilingMelee
*/

// GameplayAbilityBlueprintGeneratedClass /Game/Abilities/NPC/Blaster/GAB_BlasterCeilingMelee.GAB_BlasterCeilingMelee_C
// 0x0000 (0x06EC)
class UGAB_BlasterCeilingMelee_C : public UGAB_HuskyHuskCeilingMelee_C
{
public:
	static class UClass* StaticClass();
};

