#pragma once
#include "FN_Basic.h"

#include "FN_GAB_ATLASZap_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GAB_ATLASZapHigh
*/

// GameplayAbilityBlueprintGeneratedClass /Game/Abilities/NPC/Generic/GAB_ATLASZapHigh.GAB_ATLASZapHigh_C
// 0x0000 (0x06E8)
class UGAB_ATLASZapHigh_C : public UGAB_ATLASZap_C
{
public:
	static class UClass* StaticClass();
};

