#pragma once
#include "FN_Basic.h"

#include "FN_GET_Cooldown_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Ninja_ThrowingStarsCooldown
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Ninja/Gadgets/ThrowingStars/GE_Ninja_ThrowingStarsCooldown.GE_Ninja_ThrowingStarsCooldown_C
// 0x0000 (0x0368)
class UGE_Ninja_ThrowingStarsCooldown_C : public UGET_Cooldown_C
{
public:
	static class UClass* StaticClass();
};

