#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_FlingerMeleeSwipeCooldown
*/

// BlueprintGeneratedClass /Game/Abilities/NPC/Flinger/GE_FlingerMeleeSwipeCooldown.GE_FlingerMeleeSwipeCooldown_C
// 0x0000 (0x0368)
class UGE_FlingerMeleeSwipeCooldown_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

