#pragma once
#include "FN_Basic.h"

#include "FN_GET_Cooldown_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Commando_ShockwaveCooldown
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Commando/Gadgets/Shockwave/GE_Commando_ShockwaveCooldown.GE_Commando_ShockwaveCooldown_C
// 0x0000 (0x0368)
class UGE_Commando_ShockwaveCooldown_C : public UGET_Cooldown_C
{
public:
	static class UClass* StaticClass();
};

