#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Homebase_Rating_FiringRange
*/

// BlueprintGeneratedClass /Game/Abilities/Homebase/Rating/GE_Homebase_Rating_FiringRange.GE_Homebase_Rating_FiringRange_C
// 0x0000 (0x0368)
class UGE_Homebase_Rating_FiringRange_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

