#pragma once
#include "FN_Basic.h"

#include "FN_GET_PeriodicEnergyDamage_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Constructor_ContainmentUnitDamage
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Constructor/Gadgets/BASE/GE_Constructor_ContainmentUnitDamage.GE_Constructor_ContainmentUnitDamage_C
// 0x0000 (0x0368)
class UGE_Constructor_ContainmentUnitDamage_C : public UGET_PeriodicEnergyDamage_C
{
public:
	static class UClass* StaticClass();
};

