#pragma once
#include "FN_Basic.h"

#include "FN_GAT_GenericActiveAbility_parameters.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_GAT_ActiveAbility_classes.h"
#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GAT_GenericActiveAbility
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Parents/GAT_GenericActiveAbility.GAT_GenericActiveAbility_C
// 0x0060 (0x0740)
class UGAT_GenericActiveAbility_C : public UGAT_ActiveAbility_C
{
public:
	FPointerToUberGraphFrame                                                                             UberGraphFrame;                                    // 0x06E0 (0x0004)
	FGameplayEventData                                                                                   EventData;                                         // 0x06E4 (0x0058)
	class AFortPlayerPawn*                                                                               FortPlayerPawn;                                    // 0x073C (0x0004)
public:
	void K2_ActivateAbility(); // Function /Game/Abilities/Player/Parents/GAT_GenericActiveAbility.GAT_GenericActiveAbility_C:K2_ActivateAbility
	void ExecuteUbergraph_GAT_GenericActiveAbility(int32_t EntryPoint); // Function /Game/Abilities/Player/Parents/GAT_GenericActiveAbility.GAT_GenericActiveAbility_C:ExecuteUbergraph_GAT_GenericActiveAbility
public:
	static class UClass* StaticClass();
};

