#pragma once
#include "FN_Basic.h"

#include "FN_GET_Cooldown_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Generic_ProximityMinesCooldown
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Generic/Gadgets/Proximity_Mines/GE_Generic_ProximityMinesCooldown.GE_Generic_ProximityMinesCooldown_C
// 0x0000 (0x0368)
class UGE_Generic_ProximityMinesCooldown_C : public UGET_Cooldown_C
{
public:
	static class UClass* StaticClass();
};

