#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_TrapCooldownGeneric
*/

// BlueprintGeneratedClass /Game/Abilities/Traps/Generic/GE_TrapCooldownGeneric.GE_TrapCooldownGeneric_C
// 0x0000 (0x0368)
class UGE_TrapCooldownGeneric_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

