#pragma once
#include "FN_Basic.h"

#include "FN_GET_PeriodicCreatureDamage_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_HuskAOE3DOTPoison
*/

// BlueprintGeneratedClass /Game/Abilities/NPC/Husk/Base/GE_HuskAOE3DOTPoison.GE_HuskAOE3DOTPoison_C
// 0x0000 (0x0368)
class UGE_HuskAOE3DOTPoison_C : public UGET_PeriodicCreatureDamage_C
{
public:
	static class UClass* StaticClass();
};

