#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Homebase_ExplorersGuild_WorkerBonus
*/

// BlueprintGeneratedClass /Game/Abilities/Homebase/Static/ExplorersGuild/GE_Homebase_ExplorersGuild_WorkerBonus.GE_Homebase_ExplorersGuild_WorkerBonus_C
// 0x0000 (0x0368)
class UGE_Homebase_ExplorersGuild_WorkerBonus_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

