#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_ShieldRegen_Delay_Damaged
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Generic/GameplayEffects/GE_ShieldRegen_Delay_Damaged.GE_ShieldRegen_Delay_Damaged_C
// 0x0000 (0x0368)
class UGE_ShieldRegen_Delay_Damaged_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

