#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_HuskBeehiveAOE4Remove
*/

// BlueprintGeneratedClass /Game/Abilities/NPC/Husk/Beehive/GE_HuskBeehiveAOE4Remove.GE_HuskBeehiveAOE4Remove_C
// 0x0000 (0x0368)
class UGE_HuskBeehiveAOE4Remove_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

