#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: GE_Generic_ShieldRegen
*/

// BlueprintGeneratedClass /Game/Abilities/Player/Generic/GameplayEffects/GE_Generic_ShieldRegen.GE_Generic_ShieldRegen_C
// 0x0000 (0x0368)
class UGE_Generic_ShieldRegen_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

