#pragma once
#include "FN_Basic.h"

#include "FN_MyTown_Building_Master_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: HB_Gym_2
*/

// BlueprintGeneratedClass /Game/Environments/Homebase/Blueprints/HB_Gym_2.HB_Gym_2_C
// 0x0000 (0x0510)
class AHB_Gym_2_C : public AMyTown_Building_Master_C
{
public:
	static class UClass* StaticClass();
};

