#pragma once
#include "FN_Basic.h"

#include "FN_MyTown_Building_Master_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: HB_Hero_Constructor_5
*/

// BlueprintGeneratedClass /Game/Environments/Homebase/Blueprints/HB_Hero_Constructor_5.HB_Hero_Constructor_5_C
// 0x0000 (0x0510)
class AHB_Hero_Constructor_5_C : public AMyTown_Building_Master_C
{
public:
	static class UClass* StaticClass();
};

