#pragma once
#include "FN_Basic.h"

#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"
#include "FN_FortniteGame_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: LlamaFortDecoTool
*/

// BlueprintGeneratedClass /Game/Weapons/FORT_BuildingTools/Blueprints/LlamaFortDecoTool.LlamaFortDecoTool_C
// 0x0000 (0x0640)
class ALlamaFortDecoTool_C : public AFortCustomizableAbilityDecoTool
{
public:
	static class UClass* StaticClass();
};

