#pragma once
#include "FN_Basic.h"

#include "FN_MovieWidget_parameters.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_FortniteUI_enums.h"
#include "FN_FortniteUI_structs.h"
#include "FN_FortniteUI_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: MovieWidget
*/

// WidgetBlueprintGeneratedClass /Game/UI/Building/MovieWidget.MovieWidget_C
// 0x000C (0x0254)
class UMovieWidget_C : public UFortMovieWidget
{
public:
	FPointerToUberGraphFrame                                                                             UberGraphFrame;                                    // 0x0248 (0x0004)
	class UBorder*                                                                                       Video_Border;                                      // 0x024C (0x0004)
	class USizeBox*                                                                                      Video_SizeBox;                                     // 0x0250 (0x0004)
public:
	void StopPlaying(); // Function /Game/UI/Building/MovieWidget.MovieWidget_C:StopPlaying
	void Init(class UMediaTexture* inMediaTexture); // Function /Game/UI/Building/MovieWidget.MovieWidget_C:Init
	void Destruct(); // Function /Game/UI/Building/MovieWidget.MovieWidget_C:Destruct
	void ExecuteUbergraph_MovieWidget(int32_t EntryPoint); // Function /Game/UI/Building/MovieWidget.MovieWidget_C:ExecuteUbergraph_MovieWidget
public:
	static class UClass* StaticClass();
};

