#pragma once
#include "FN_Basic.h"


/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: MyTown_BuildingGroups
*/

// UserDefinedStruct /Game/Environments/Homebase/Structs/MyTown_BuildingGroups.MyTown_BuildingGroups
// 0x001C (0x001C)
struct FMyTown_BuildingGroups
{
	TArray<class AMyTownBuildingActor*>                                                                  BuildingGroupsArray_39_DD52A83B4AA3691ABC472E8B70290210; // 0x0000 (0x000C)
	TArray<class UMaterialInstanceDynamic*>                                                              BuildingMaterialArray_44_3A0C66FD4A70D5026F5E12A2C304DACE; // 0x000C (0x000C)
	class UTexture2D*                                                                                    UIIconTexture_49_586D92D746767BA2F99FDBB51B2B59DA; // 0x0018 (0x0004)

	static class UScriptStruct* StaticStruct();
};

