#pragma once
#include "FN_Basic.h"

#include "FN_SlateCore_enums.h"
#include "FN_SlateCore_structs.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: ModalQueueEntry
*/

// UserDefinedStruct /Game/UI/Global_Elements/ModalQueueEntry.ModalQueueEntry
// 0x0006 (0x0006)
struct FModalQueueEntry
{
	class UFortActionHandlerPanel*                                                                       ModalWidget_6_ABD0CAFC486CC76BD82B05A35CCE76CF;    // 0x0000 (0x0004)
	EHorizontalAlignment                                                                                 HorizontalAlignment_7_B47CAE52460FA9A3472426927E37F9D2; // 0x0004 (0x0001)
	EVerticalAlignment                                                                                   VerticalAlignment_8_68F491E04BAAE1E2897BC8A9C0262FC4; // 0x0005 (0x0001)

	static class UScriptStruct* StaticStruct();
};

