#pragma once
#include "FN_Basic.h"

#include "FN_MyTown_Building_Master_parameters.h"
#include "FN_CoreUObject_enums.h"
#include "FN_CoreUObject_structs.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"
#include "FN_FortniteGame_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: MyTown_Building_Master
*/

// BlueprintGeneratedClass /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C
// 0x0238 (0x0510)
class AMyTown_Building_Master_C : public AMyTownBuildingActor
{
public:
	FPointerToUberGraphFrame                                                                             UberGraphFrame;                                    // 0x02D8 (0x0004)
	class UStaticMeshComponent*                                                                          Flag;                                              // 0x02DC (0x0004)
	class UStaticMeshComponent*                                                                          GroundMesh;                                        // 0x02E0 (0x0004)
	class UStaticMeshComponent*                                                                          BuildBox;                                          // 0x02E4 (0x0004)
	class UStaticMeshComponent*                                                                          BuildBox_WallX;                                    // 0x02E8 (0x0004)
	class UStaticMeshComponent*                                                                          BuildBox_Pop;                                      // 0x02EC (0x0004)
	class UStaticMeshComponent*                                                                          BuildBox_WallZ;                                    // 0x02F0 (0x0004)
	class UStaticMeshComponent*                                                                          BuildBox_Morph;                                    // 0x02F4 (0x0004)
	class UStaticMeshComponent*                                                                          BuildBox_WallBY;                                   // 0x02F8 (0x0004)
	class UStaticMeshComponent*                                                                          BuildBox_WallBX;                                   // 0x02FC (0x0004)
	class UStaticMeshComponent*                                                                          BuildBox_WallY;                                    // 0x0300 (0x0004)
	class UStaticMeshComponent*                                                                          HoloBuilding;                                      // 0x0304 (0x0004)
	class UStaticMeshComponent*                                                                          HoverBox;                                          // 0x0308 (0x0004)
	class UStaticMeshComponent*                                                                          UpgradeMesh;                                       // 0x030C (0x0004)
	class UStaticMeshComponent*                                                                          UpgradeGlow;                                       // 0x0310 (0x0004)
	class UStaticMeshComponent*                                                                          Platform;                                          // 0x0314 (0x0004)
	class UStaticMeshComponent*                                                                          Lock;                                              // 0x0318 (0x0004)
	float                                                                                                AddWorkerAnimation_TL_WorkerFlash_BC2A05C3422A64750F9305A3348D77AB; // 0x031C (0x0004)
	ETimelineDirection                                                                                   AddWorkerAnimation_TL__Direction_BC2A05C3422A64750F9305A3348D77AB; // 0x0320 (0x0001)
	uint8_t                                                                                              UnknownData_321[0x3];                              // 0x0321 (0x0003) MISSED OFFSET
	class UTimelineComponent*                                                                            AddWorkerAnimation_TL;                             // 0x0324 (0x0004)
	float                                                                                                BuildingUpgrade_TL_Flash_022B1B3F407E08B018D67C85D55D6353; // 0x0328 (0x0004)
	float                                                                                                BuildingUpgrade_TL_Squash_and_Stretch_022B1B3F407E08B018D67C85D55D6353; // 0x032C (0x0004)
	ETimelineDirection                                                                                   BuildingUpgrade_TL__Direction_022B1B3F407E08B018D67C85D55D6353; // 0x0330 (0x0001)
	uint8_t                                                                                              UnknownData_331[0x3];                              // 0x0331 (0x0003) MISSED OFFSET
	class UTimelineComponent*                                                                            BuildingUpgrade_TL;                                // 0x0334 (0x0004)
	float                                                                                                BubblePop_BubblePop_024074C647081B54E9FAC5B8E9DEF552; // 0x0338 (0x0004)
	ETimelineDirection                                                                                   BubblePop__Direction_024074C647081B54E9FAC5B8E9DEF552; // 0x033C (0x0001)
	uint8_t                                                                                              UnknownData_33D[0x3];                              // 0x033D (0x0003) MISSED OFFSET
	class UTimelineComponent*                                                                            BubblePop;                                         // 0x0340 (0x0004)
	float                                                                                                BuildingFlashOut_BuildSquash_CADEA3F846AC0FDB2452EAB45F6A550B; // 0x0344 (0x0004)
	float                                                                                                BuildingFlashOut_NewBuildFlash_CADEA3F846AC0FDB2452EAB45F6A550B; // 0x0348 (0x0004)
	ETimelineDirection                                                                                   BuildingFlashOut__Direction_CADEA3F846AC0FDB2452EAB45F6A550B; // 0x034C (0x0001)
	uint8_t                                                                                              UnknownData_34D[0x3];                              // 0x034D (0x0003) MISSED OFFSET
	class UTimelineComponent*                                                                            BuildingFlashOut;                                  // 0x0350 (0x0004)
	float                                                                                                MorphPop_Jiggle_C9DB9DF84601DDB0B713EC9510BDD141;  // 0x0354 (0x0004)
	float                                                                                                MorphPop_Distortion_C9DB9DF84601DDB0B713EC9510BDD141; // 0x0358 (0x0004)
	float                                                                                                MorphPop_Fade_C9DB9DF84601DDB0B713EC9510BDD141;    // 0x035C (0x0004)
	float                                                                                                MorphPop_MorphPop_C9DB9DF84601DDB0B713EC9510BDD141; // 0x0360 (0x0004)
	ETimelineDirection                                                                                   MorphPop__Direction_C9DB9DF84601DDB0B713EC9510BDD141; // 0x0364 (0x0001)
	uint8_t                                                                                              UnknownData_365[0x3];                              // 0x0365 (0x0003) MISSED OFFSET
	class UTimelineComponent*                                                                            MorphPop;                                          // 0x0368 (0x0004)
	float                                                                                                BuildAnim_Walls_TL_Wall_B_Y_A8958F34498B607B5D0BAA9C6B3A1E6F; // 0x036C (0x0004)
	float                                                                                                BuildAnim_Walls_TL_Wall_B_X_A8958F34498B607B5D0BAA9C6B3A1E6F; // 0x0370 (0x0004)
	float                                                                                                BuildAnim_Walls_TL_Wall_Z_A8958F34498B607B5D0BAA9C6B3A1E6F; // 0x0374 (0x0004)
	float                                                                                                BuildAnim_Walls_TL_Wall_Y_A8958F34498B607B5D0BAA9C6B3A1E6F; // 0x0378 (0x0004)
	float                                                                                                BuildAnim_Walls_TL_Wall_X_A8958F34498B607B5D0BAA9C6B3A1E6F; // 0x037C (0x0004)
	ETimelineDirection                                                                                   BuildAnim_Walls_TL__Direction_A8958F34498B607B5D0BAA9C6B3A1E6F; // 0x0380 (0x0001)
	uint8_t                                                                                              UnknownData_381[0x3];                              // 0x0381 (0x0003) MISSED OFFSET
	class UTimelineComponent*                                                                            BuildAnim_Walls_TL;                                // 0x0384 (0x0004)
	float                                                                                                SquashAndStretchIn_TL_fFadeIn_F65A50F9485109D050DA48A27CA90AF5; // 0x0388 (0x0004)
	float                                                                                                SquashAndStretchIn_TL_fSquashIn_F65A50F9485109D050DA48A27CA90AF5; // 0x038C (0x0004)
	ETimelineDirection                                                                                   SquashAndStretchIn_TL__Direction_F65A50F9485109D050DA48A27CA90AF5; // 0x0390 (0x0001)
	uint8_t                                                                                              UnknownData_391[0x3];                              // 0x0391 (0x0003) MISSED OFFSET
	class UTimelineComponent*                                                                            SquashAndStretchIn_TL;                             // 0x0394 (0x0004)
	float                                                                                                GlobalFadeIn_TL_fGlobalFadeIn_A116FB5A4414B6F876C0289C97BD4B19; // 0x0398 (0x0004)
	ETimelineDirection                                                                                   GlobalFadeIn_TL__Direction_A116FB5A4414B6F876C0289C97BD4B19; // 0x039C (0x0001)
	uint8_t                                                                                              UnknownData_39D[0x3];                              // 0x039D (0x0003) MISSED OFFSET
	class UTimelineComponent*                                                                            GlobalFadeIn_TL;                                   // 0x03A0 (0x0004)
	float                                                                                                GlobalFadeOut_TL_fGlobalFadeOut_C7CBEBC64EA8A4A48498E792B9E9A1FF; // 0x03A4 (0x0004)
	ETimelineDirection                                                                                   GlobalFadeOut_TL__Direction_C7CBEBC64EA8A4A48498E792B9E9A1FF; // 0x03A8 (0x0001)
	uint8_t                                                                                              UnknownData_3A9[0x3];                              // 0x03A9 (0x0003) MISSED OFFSET
	class UTimelineComponent*                                                                            GlobalFadeOut_TL;                                  // 0x03AC (0x0004)
	class AMyFort_Manager_C*                                                                             MyFortManager;                                     // 0x03B0 (0x0004)
	class UMaterialInterface*                                                                            BuildingMeshMaterial;                              // 0x03B4 (0x0004)
	class AHB_RoadManager_C*                                                                             RoadManager;                                       // 0x03B8 (0x0004)
	bool                                                                                                 IsSubBuilding;                                     // 0x03BC (0x0001)
	uint8_t                                                                                              UnknownData_3BD[0x3];                              // 0x03BD (0x0003) MISSED OFFSET
	class UStaticMesh*                                                                                   LockedState;                                       // 0x03C0 (0x0004)
	float                                                                                                LockZRot;                                          // 0x03C4 (0x0004)
	class UStaticMesh*                                                                                   UnBuiltMesh;                                       // 0x03C8 (0x0004)
	int32_t                                                                                              BuildingId;                                        // 0x03CC (0x0004)
	class UMaterialInstanceDynamic*                                                                      PlatformMID;                                       // 0x03D0 (0x0004)
	bool                                                                                                 DebugStates;                                       // 0x03D4 (0x0001)
	uint8_t                                                                                              UnknownData_3D5[0x3];                              // 0x03D5 (0x0003) MISSED OFFSET
	class UMaterialInstanceDynamic*                                                                      BuildingMID;                                       // 0x03D8 (0x0004)
	class UMaterialInstanceDynamic*                                                                      HoverBoxMID;                                       // 0x03DC (0x0004)
	class UMaterialInstanceDynamic*                                                                      LockMID;                                           // 0x03E0 (0x0004)
	FLinearColor                                                                                         Black;                                             // 0x03E4 (0x0010)
	class UMaterialInstanceDynamic*                                                                      UnbuiltMaterialMID;                                // 0x03F4 (0x0004)
	FLinearColor                                                                                         LockedSelectionHover1;                             // 0x03F8 (0x0010)
	FLinearColor                                                                                         LockedSelectionHover2;                             // 0x0408 (0x0010)
	FLinearColor                                                                                         IdleHover1;                                        // 0x0418 (0x0010)
	FLinearColor                                                                                         IdleHover2;                                        // 0x0428 (0x0010)
	FLinearColor                                                                                         UpgradeHover1;                                     // 0x0438 (0x0010)
	FLinearColor                                                                                         UpgradeHover2;                                     // 0x0448 (0x0010)
	FVector                                                                                              HoloBuildingOffset;                                // 0x0458 (0x000C)
	bool                                                                                                 MenuOpened;                                        // 0x0464 (0x0001)
	bool                                                                                                 HoverAnimComplete;                                 // 0x0465 (0x0001)
	uint8_t                                                                                              UnknownData_466[0x2];                              // 0x0466 (0x0002) MISSED OFFSET
	class UMaterialInstanceDynamic*                                                                      WallXMID;                                          // 0x0468 (0x0004)
	class UMaterialInstanceDynamic*                                                                      WallYMID;                                          // 0x046C (0x0004)
	class UMaterialInstanceDynamic*                                                                      WallBXMID;                                         // 0x0470 (0x0004)
	class UMaterialInstanceDynamic*                                                                      WallBYMID;                                         // 0x0474 (0x0004)
	class UMaterialInstanceDynamic*                                                                      WallMorphMID;                                      // 0x0478 (0x0004)
	class UMaterialInstanceDynamic*                                                                      BuildBoxMID;                                       // 0x047C (0x0004)
	class UMaterialInstanceDynamic*                                                                      WallZMID;                                          // 0x0480 (0x0004)
	class UMaterialInstanceDynamic*                                                                      WallMorphBackMID;                                  // 0x0484 (0x0004)
	class UMaterialInstanceDynamic*                                                                      PopMID;                                            // 0x0488 (0x0004)
	bool                                                                                                 BuildingisBuilt;                                   // 0x048C (0x0001)
	uint8_t                                                                                              UnknownData_48D[0x3];                              // 0x048D (0x0003) MISSED OFFSET
	FLinearColor                                                                                         LockedIdleColor1;                                  // 0x0490 (0x0010)
	FLinearColor                                                                                         LockedIdleColor2;                                  // 0x04A0 (0x0010)
	int32_t                                                                                              InitialLevel;                                      // 0x04B0 (0x0004)
	bool                                                                                                 bAnimating;                                        // 0x04B4 (0x0001)
	bool                                                                                                 TutorialBuilding;                                  // 0x04B5 (0x0001)
	uint8_t                                                                                              UnknownData_4B6[0x2];                              // 0x04B6 (0x0002) MISSED OFFSET
	FVector2D                                                                                            TutorialCommandoScreenPos;                         // 0x04B8 (0x0008)
	FLinearColor                                                                                         IdleUnbuiltHover1;                                 // 0x04C0 (0x0010)
	FLinearColor                                                                                         IdleUnbuiltHover2;                                 // 0x04D0 (0x0010)
	FVector2D                                                                                            TutorialConstructorScreenPos;                      // 0x04E0 (0x0008)
	float                                                                                                TutorialCommandoDist;                              // 0x04E8 (0x0004)
	float                                                                                                TutorialConstructorDist;                           // 0x04EC (0x0004)
	bool                                                                                                 inTutorial;                                        // 0x04F0 (0x0001)
	uint8_t                                                                                              UnknownData_4F1[0x3];                              // 0x04F1 (0x0003) MISSED OFFSET
	FVector2D                                                                                            SavedZoom;                                         // 0x04F4 (0x0008)
	float                                                                                                SavedDist;                                         // 0x04FC (0x0004)
	bool                                                                                                 UpgradePath;                                       // 0x0500 (0x0001)
	uint8_t                                                                                              UnknownData_501[0x3];                              // 0x0501 (0x0003) MISSED OFFSET
	class UParticleSystemComponent*                                                                      BuildBuilding_LightEmitter;                        // 0x0504 (0x0004)
	bool                                                                                                 HasBanner;                                         // 0x0508 (0x0001)
	uint8_t                                                                                              UnknownData_509[0x3];                              // 0x0509 (0x0003) MISSED OFFSET
	class UMaterialInstanceDynamic*                                                                      NewVar;                                            // 0x050C (0x0004)
public:
	void StencilBufferSetup(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:StencilBufferSetup
	void UpdateBangVisibility(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:UpdateBangVisibility
	void Set_Tooltip_Visibility(bool Visibile); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:Set Tooltip Visibility
	void Setup_Tooltip(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:Setup Tooltip
	void UpgradeIconFriendCheck(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:UpgradeIconFriendCheck
	void MIDCreation(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:MIDCreation
	void StateDebug_Build(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:StateDebug Build
	void StateDebug_Upgrade(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:StateDebug Upgrade
	void StateDebug_Idle(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:StateDebug_Idle
	void State_Debug_Locked(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:State Debug Locked
	void HasBeenBuilt(bool Building_is_Built, int32_t Building_Level); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:HasBeenBuilt
	void UserConstructionScript(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:UserConstructionScript
	void GlobalFadeOut_TL__FinishedFunc(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:GlobalFadeOut_TL__FinishedFunc
	void GlobalFadeOut_TL__UpdateFunc(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:GlobalFadeOut_TL__UpdateFunc
	void GlobalFadeIn_TL__FinishedFunc(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:GlobalFadeIn_TL__FinishedFunc
	void GlobalFadeIn_TL__UpdateFunc(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:GlobalFadeIn_TL__UpdateFunc
	void SquashAndStretchIn_TL__FinishedFunc(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:SquashAndStretchIn_TL__FinishedFunc
	void SquashAndStretchIn_TL__UpdateFunc(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:SquashAndStretchIn_TL__UpdateFunc
	void BuildAnim_Walls_TL__FinishedFunc(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:BuildAnim_Walls_TL__FinishedFunc
	void BuildAnim_Walls_TL__UpdateFunc(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:BuildAnim_Walls_TL__UpdateFunc
	void MorphPop__FinishedFunc(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:MorphPop__FinishedFunc
	void MorphPop__UpdateFunc(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:MorphPop__UpdateFunc
	void MorphPop__SpawnLightEmitter__EventFunc(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:MorphPop__SpawnLightEmitter__EventFunc
	void BuildingFlashOut__FinishedFunc(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:BuildingFlashOut__FinishedFunc
	void BuildingFlashOut__UpdateFunc(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:BuildingFlashOut__UpdateFunc
	void BubblePop__FinishedFunc(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:BubblePop__FinishedFunc
	void BubblePop__UpdateFunc(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:BubblePop__UpdateFunc
	void BuildingUpgrade_TL__FinishedFunc(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:BuildingUpgrade_TL__FinishedFunc
	void BuildingUpgrade_TL__UpdateFunc(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:BuildingUpgrade_TL__UpdateFunc
	void AddWorkerAnimation_TL__FinishedFunc(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:AddWorkerAnimation_TL__FinishedFunc
	void AddWorkerAnimation_TL__UpdateFunc(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:AddWorkerAnimation_TL__UpdateFunc
	void GlobalFadeOut(class UMaterialInstanceDynamic* Mid, FName Parameter, bool Parameter_Collection); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:GlobalFadeOut
	void GlobalFadeIn(class UMaterialInstanceDynamic* Mid, FName Parameter, bool Parameter_Collection); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:GlobalFadeIn
	void HoloHoverAnim(class UMaterialInstanceDynamic* MID_Array, float SquashIntensity); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:HoloHoverAnim
	void BuildingAnimation(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:BuildingAnimation
	void BuildSubbuildingAnimation(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:BuildSubbuildingAnimation
	void BuildingUpgradeAnimation(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:BuildingUpgradeAnimation
	void AddWorkerAnimation(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:AddWorkerAnimation
	void idle(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:idle
	void CanUpgrade(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:CanUpgrade
	void Locked(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:Locked
	void CanBuild(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:CanBuild
	void Idle_Cursor_Over(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:Idle Cursor Over
	void Idle_CursorOut(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:Idle CursorOut
	void CanBuildOver(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:CanBuildOver
	void CanBuildOut(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:CanBuildOut
	void LockedOver(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:LockedOver
	void LockedOut(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:LockedOut
	void HoloBuildingMeshAssign(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:HoloBuildingMeshAssign
	void HoloBuildingRotation(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:HoloBuildingRotation
	void HoloBuildingAnim(float Time); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:HoloBuildingAnim
	void CanUpgradeOver(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:CanUpgradeOver
	void CanUpgradeOut(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:CanUpgradeOut
	void IdleOpen(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:IdleOpen
	void IdleClosed(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:IdleClosed
	void CanBuildOpen(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:CanBuildOpen
	void CanBuildClosed(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:CanBuildClosed
	void LockedOpen(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:LockedOpen
	void LockedClosed(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:LockedClosed
	void CanUpgradeOpen(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:CanUpgradeOpen
	void CanUpgradeClosed(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:CanUpgradeClosed
	void BuildBuilding(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:BuildBuilding
	void UpgradeBuilding(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:UpgradeBuilding
	void ReceiveBeginPlay(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:ReceiveBeginPlay
	void SetUnbuiltPlatformIcon(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:SetUnbuiltPlatformIcon
	void MyTown_BuildingStates(FString Building_Template_ID); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:MyTown_BuildingStates
	void OnMyTownBuildingStateChanged_Event_0(EMyTownBuildingState NewState, EMyTownBuildingState OldState); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:OnMyTownBuildingStateChanged_Event_0
	void OnBeginCursorOver_Event_1(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:OnBeginCursorOver_Event_1
	void OnEndCursorOver_Event_1(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:OnEndCursorOver_Event_1
	void CheckCollision(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:CheckCollision
	void UpdateRoads(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:UpdateRoads
	void OnMyTownBuildingPanelOpened_Event_0(FString BuildingTemplateId); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:OnMyTownBuildingPanelOpened_Event_0
	void OnMyTownBuildingPanelClosed_Event_0(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:OnMyTownBuildingPanelClosed_Event_0
	void OnMyTownBuildingWorkersChanged_Event_0(FString BuildingTemplateId); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:OnMyTownBuildingWorkersChanged_Event_0
	void OnMyTownBuildingUpgradeFinished_Event_0(FString BuildingTemplateId, bool bSuccess); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:OnMyTownBuildingUpgradeFinished_Event_0
	void SetFlagIcon(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:SetFlagIcon
	void OnBuildingInfoUpdated(); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:OnBuildingInfoUpdated
	void HandleClientEvent_OnboardingBuildingsStage1(class UObject* EventSource, class UObject* EventFocus, FFortClientEvent ClientEvent); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:HandleClientEvent_OnboardingBuildingsStage1
	void HandleClientEvent_OnboardingBuildingsStage2(class UObject* EventSource, class UObject* EventFocus, FFortClientEvent ClientEvent); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:HandleClientEvent_OnboardingBuildingsStage2
	void HandleClientEvent_OnboardingBuildingsStage3(class UObject* EventSource, class UObject* EventFocus, FFortClientEvent ClientEvent); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:HandleClientEvent_OnboardingBuildingsStage3
	void ExecuteUbergraph_MyTown_Building_Master(int32_t EntryPoint); // Function /Game/Environments/Homebase/Blueprints/MyTown_Building_Master.MyTown_Building_Master_C:ExecuteUbergraph_MyTown_Building_Master
public:
	static class UClass* StaticClass();
};

