#pragma once
#include "FN_Basic.h"


/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: RoadPathConnections
*/

// UserDefinedEnum /Game/Environments/Homebase/Blueprints/RoadPathConnections.RoadPathConnections
enum class RoadPathConnections : uint8_t
{
	NewEnumerator0                                     = 0,
	NewEnumerator1                                     = 1,
	NewEnumerator2                                     = 2,
	NewEnumerator3                                     = 3,
	NewEnumerator4                                     = 4,
	NewEnumerator5                                     = 5,
	NewEnumerator6                                     = 6,
	NewEnumerator7                                     = 7,
	NewEnumerator8                                     = 8,
	NewEnumerator9                                     = 9,
	NewEnumerator10                                    = 10,
	NewEnumerator11                                    = 11,
	RoadPathConnections_MAX                            = 12
};

