#pragma once
#include "FN_Basic.h"

#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: SetBonus_TrapDamage_Low
*/

// BlueprintGeneratedClass /Game/Abilities/Homebase/Personnel/SetBonuses/SetBonus_TrapDamage_Low.SetBonus_TrapDamage_Low_C
// 0x0000 (0x0368)
class USetBonus_TrapDamage_Low_C : public UGameplayEffect
{
public:
	static class UClass* StaticClass();
};

