#pragma once
#include "FN_Basic.h"


/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: StructRecyclingResource
*/

// UserDefinedStruct /Game/Abilities/Player/Constructor/Gadgets/BASE/StructRecyclingResource.StructRecyclingResource
// 0x0008 (0x0008)
struct FStructRecyclingResource
{
	class UFortWorldItemDefinition*                                                                      ResourceType_6_1CB0341449EA85C60677C6B2035AFAAD;   // 0x0000 (0x0004)
	int32_t                                                                                              AmountStored_5_ADCE813746D841E0568B169628A9BFDA;   // 0x0004 (0x0004)

	static class UScriptStruct* StaticStruct();
};

