#pragma once
#include "FN_Basic.h"

#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"
#include "FN_FortniteGame_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: SmasherStrength01
*/

// BlueprintGeneratedClass /Game/Building/NavigationAreas/SmasherStrength01.SmasherStrength01_C
// 0x0000 (0x0054)
class USmasherStrength01_C : public UFortNavAreaAutomatic
{
public:
	static class UClass* StaticClass();
};

