#pragma once
#include "FN_Basic.h"

#include "FN_StartForgettingGoal_parameters.h"
#include "FN_AIModule_enums.h"
#include "FN_AIModule_structs.h"
#include "FN_AIModule_classes.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: StartForgettingGoal
*/

// BlueprintGeneratedClass /Game/AI/BehaviorTrees/Tasks/StartForgettingGoal.StartForgettingGoal_C
// 0x0004 (0x0060)
class UStartForgettingGoal_C : public UBTTask_BlueprintBase
{
public:
	FPointerToUberGraphFrame                                                                             UberGraphFrame;                                    // 0x005C (0x0004)
public:
	void ReceiveExecute(class AActor* OwnerActor); // Function /Game/AI/BehaviorTrees/Tasks/StartForgettingGoal.StartForgettingGoal_C:ReceiveExecute
	void ExecuteUbergraph_StartForgettingGoal(int32_t EntryPoint); // Function /Game/AI/BehaviorTrees/Tasks/StartForgettingGoal.StartForgettingGoal_C:ExecuteUbergraph_StartForgettingGoal
public:
	static class UClass* StaticClass();
};

