#pragma once
#include "FN_Basic.h"

#include "FN_Survive_Notification_Health_parameters.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"
#include "FN_FortniteGame_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: Survive_Notification_Health
*/

// BlueprintGeneratedClass /Game/Blueprints/Adventures/SurviveTheStorm/Notifications/Survive_Notification_Health.Survive_Notification_Health_C
// 0x0008 (0x0424)
class ASurvive_Notification_Health_C : public AFortClientNotification
{
public:
	FPointerToUberGraphFrame                                                                             UberGraphFrame;                                    // 0x041C (0x0004)
	class USceneComponent*                                                                               DefaultSceneRoot;                                  // 0x0420 (0x0004)
public:
	void UserConstructionScript(); // Function /Game/Blueprints/Adventures/SurviveTheStorm/Notifications/Survive_Notification_Health.Survive_Notification_Health_C:UserConstructionScript
	void OnNotificationStart(); // Function /Game/Blueprints/Adventures/SurviveTheStorm/Notifications/Survive_Notification_Health.Survive_Notification_Health_C:OnNotificationStart
	void ExecuteUbergraph_Survive_Notification_Health(int32_t EntryPoint); // Function /Game/Blueprints/Adventures/SurviveTheStorm/Notifications/Survive_Notification_Health.Survive_Notification_Health_C:ExecuteUbergraph_Survive_Notification_Health
public:
	static class UClass* StaticClass();
};

