#pragma once
#include "FN_Basic.h"

#include "FN_FortniteGame_enums.h"
#include "FN_FortniteGame_structs.h"
#include "FN_FortniteGame_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: Targeting3PCamera_Scope
*/

// BlueprintGeneratedClass /Game/Blueprints/Camera/Original/Targeting3PCamera_Scope.Targeting3PCamera_Scope_C
// 0x0000 (0x0110)
class UTargeting3PCamera_Scope_C : public UFort3PCam_Targeting
{
public:
	static class UClass* StaticClass();
};

