#pragma once
#include "FN_Basic.h"

#include "FN_ThrowingStarTest_parameters.h"
#include "FN_GameplayAbilities_enums.h"
#include "FN_GameplayAbilities_structs.h"
#include "FN_GameplayAbilities_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: ThrowingStarTest
*/

// BlueprintGeneratedClass /Game/GameplayCueNotifies/ThrowingStarTest.ThrowingStarTest_C
// 0x0000 (0x0030)
class UThrowingStarTest_C : public UGameplayCueNotify_Static
{
public:
	bool OnExecute(class AActor* MyTarget, FGameplayCueParameters Parameters); // Function /Game/GameplayCueNotifies/ThrowingStarTest.ThrowingStarTest_C:OnExecute
public:
	static class UClass* StaticClass();
};

