#pragma once
#include "FN_Basic.h"

#include "FN_WeaponTooltipStatType_enums.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: TooltipStat
*/

// UserDefinedStruct /Game/UI/Global_Elements/TooltipStat.TooltipStat
// 0x0019 (0x0019)
struct FTooltipStat
{
	FText                                                                                                Label_2_C7826979463D342B4FA77287F6F27668;          // 0x0000 (0x000C)
	FText                                                                                                Value_5_A69E21C0475825796408CA9813F2A8B8;          // 0x000C (0x000C)
	WeaponTooltipStatType                                                                                Type_10_56B7498643DBED962C2AB6876B3FA6DC;          // 0x0018 (0x0001)

	static class UScriptStruct* StaticStruct();
};

