#pragma once
#include "FN_Basic.h"

#include "FN_TutorialOverlay_parameters.h"
#include "FN_Engine_enums.h"
#include "FN_Engine_structs.h"
#include "FN_FortniteUI_enums.h"
#include "FN_FortniteUI_structs.h"
#include "FN_FortniteUI_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: TutorialOverlay
*/

// WidgetBlueprintGeneratedClass /Game/UI/Onboarding/TutorialOverlay.TutorialOverlay_C
// 0x000C (0x0260)
class UTutorialOverlay_C : public UFortTutorialOverlay
{
public:
	FPointerToUberGraphFrame                                                                             UberGraphFrame;                                    // 0x0254 (0x0004)
	class UNamedSlot*                                                                                    NativeWidgets;                                     // 0x0258 (0x0004)
	class UTutorialScreen_C*                                                                             TutorialScreen;                                    // 0x025C (0x0004)
public:
	void Construct(); // Function /Game/UI/Onboarding/TutorialOverlay.TutorialOverlay_C:Construct
	void ExecuteUbergraph_TutorialOverlay(int32_t EntryPoint); // Function /Game/UI/Onboarding/TutorialOverlay.TutorialOverlay_C:ExecuteUbergraph_TutorialOverlay
public:
	static class UClass* StaticClass();
};

