#pragma once
#include "FN_Basic.h"

#include "FN_v2_PlayerCameraModeBase_classes.h"

/*
* =========================================================================================
* Generated by FortGen
* =========================================================================================
* PackageName: v2_PlayerCameraModeRanged
*/

// BlueprintGeneratedClass /Game/Blueprints/Camera/v2_OverShoulder/v2_PlayerCameraModeRanged.v2_PlayerCameraModeRanged_C
// 0x0000 (0x00B4)
class Uv2_PlayerCameraModeRanged_C : public Uv2_PlayerCameraModeBase_C
{
public:
	static class UClass* StaticClass();
};

